databases:
  - name: car-rental
    databaseName: house_rental_app_production
    user: car-rental

services:
  - type: web
    name: car-rental
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: car-rental
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false